package com.example.software.project.development.management.platform.ro;

public class FundsSearchRo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds_search_ro.last_deal_person_type
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    private Integer lastDealPersonType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds_search_ro.project_id
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds_search_ro.create_person_id
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    private Integer createPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds_search_ro.true_name
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    private String trueName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds_search_ro.last_deal_person_type
     *
     * @return the value of funds_search_ro.last_deal_person_type
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    public Integer getLastDealPersonType() {
        return lastDealPersonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds_search_ro.last_deal_person_type
     *
     * @param lastDealPersonType the value for funds_search_ro.last_deal_person_type
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    public void setLastDealPersonType(Integer lastDealPersonType) {
        this.lastDealPersonType = lastDealPersonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds_search_ro.project_id
     *
     * @return the value of funds_search_ro.project_id
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds_search_ro.project_id
     *
     * @param projectId the value for funds_search_ro.project_id
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds_search_ro.create_person_id
     *
     * @return the value of funds_search_ro.create_person_id
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    public Integer getCreatePersonId() {
        return createPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds_search_ro.create_person_id
     *
     * @param createPersonId the value for funds_search_ro.create_person_id
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    public void setCreatePersonId(Integer createPersonId) {
        this.createPersonId = createPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds_search_ro.true_name
     *
     * @return the value of funds_search_ro.true_name
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds_search_ro.true_name
     *
     * @param trueName the value for funds_search_ro.true_name
     *
     * @mbggenerated Tue Jan 26 23:52:34 CST 2021
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName == null ? null : trueName.trim();
    }
}
