package com.example.software.project.development.management.platform.po.ext;

import lombok.Data;

/**
 * @author hanhuafeng
 * @version V1.0
 * @description
 * @date 2020-02-23
 */
@Data
public class MenuExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Sun Feb 23 21:50:15 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated Sun Feb 23 21:50:15 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbggenerated Sun Feb 23 21:50:15 CST 2020
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbggenerated Sun Feb 23 21:50:15 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.pid
     *
     * @mbggenerated Sun Feb 23 21:50:15 CST 2020
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Sun Feb 23 21:50:15 CST 2020
     */
    private Integer id2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated Sun Feb 23 21:50:15 CST 2020
     */
    private String name2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbggenerated Sun Feb 23 21:50:15 CST 2020
     */
    private String icon2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbggenerated Sun Feb 23 21:50:15 CST 2020
     */
    private String url2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.pid
     *
     * @mbggenerated Sun Feb 23 21:50:15 CST 2020
     */
    private Integer pid2;
}
