package com.example.software.project.development.management.platform.po;

import java.math.BigDecimal;
import java.util.Date;

public class Funds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds.id
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds.reason
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds.price
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds.create_person_id
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    private Integer createPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds.last_deal_person_type
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    private Integer lastDealPersonType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds.create_time
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column funds.update_time
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    private Date updateTime;

    private int projectId;

    public int getProjectId() {
        return projectId;
    }

    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds.id
     *
     * @return the value of funds.id
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds.id
     *
     * @param id the value for funds.id
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds.reason
     *
     * @return the value of funds.reason
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds.reason
     *
     * @param reason the value for funds.reason
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds.price
     *
     * @return the value of funds.price
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds.price
     *
     * @param price the value for funds.price
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds.create_person_id
     *
     * @return the value of funds.create_person_id
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public Integer getCreatePersonId() {
        return createPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds.create_person_id
     *
     * @param createPersonId the value for funds.create_person_id
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public void setCreatePersonId(Integer createPersonId) {
        this.createPersonId = createPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds.last_deal_person_type
     *
     * @return the value of funds.last_deal_person_type
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public Integer getLastDealPersonType() {
        return lastDealPersonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds.last_deal_person_type
     *
     * @param lastDealPersonType the value for funds.last_deal_person_type
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public void setLastDealPersonType(Integer lastDealPersonType) {
        this.lastDealPersonType = lastDealPersonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds.create_time
     *
     * @return the value of funds.create_time
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds.create_time
     *
     * @param createTime the value for funds.create_time
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column funds.update_time
     *
     * @return the value of funds.update_time
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column funds.update_time
     *
     * @param updateTime the value for funds.update_time
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
