package com.example.software.project.development.management.platform.po;

import lombok.Data;

import java.util.Date;

@Data
public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.title
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.content
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.create_time
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    private Date createTime;


    private Integer projectId;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.title
     *
     * @return the value of log.title
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.title
     *
     * @param title the value for log.title
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.content
     *
     * @return the value of log.content
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.content
     *
     * @param content the value for log.content
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.create_time
     *
     * @return the value of log.create_time
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.create_time
     *
     * @param createTime the value for log.create_time
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
