package com.example.software.project.development.management.platform.po;

public class MiddleSubscription {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column middle_subscription.project_id
     *
     * @mbggenerated Tue Jan 26 00:28:29 CST 2021
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column middle_subscription.create_user_true_name
     *
     * @mbggenerated Tue Jan 26 00:28:29 CST 2021
     */
    private String createUserTrueName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column middle_subscription.project_id
     *
     * @return the value of middle_subscription.project_id
     *
     * @mbggenerated Tue Jan 26 00:28:29 CST 2021
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column middle_subscription.project_id
     *
     * @param projectId the value for middle_subscription.project_id
     *
     * @mbggenerated Tue Jan 26 00:28:29 CST 2021
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column middle_subscription.create_user_true_name
     *
     * @return the value of middle_subscription.create_user_true_name
     *
     * @mbggenerated Tue Jan 26 00:28:29 CST 2021
     */
    public String getCreateUserTrueName() {
        return createUserTrueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column middle_subscription.create_user_true_name
     *
     * @param createUserTrueName the value for middle_subscription.create_user_true_name
     *
     * @mbggenerated Tue Jan 26 00:28:29 CST 2021
     */
    public void setCreateUserTrueName(String createUserTrueName) {
        this.createUserTrueName = createUserTrueName == null ? null : createUserTrueName.trim();
    }
}