package com.example.software.project.development.management.platform.po;

import lombok.Data;

import java.util.Date;

@Data
public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.name
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pid
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.describe_info
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private String describeInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.duty_person_id
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private Integer dutyPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.duty_person_name
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private String dutyPersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.start_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.end_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.need_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private Integer needTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    private Date updateTime;

    /**
     * 评论数量
     */
    private int num;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.name
     *
     * @return the value of project.name
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.name
     *
     * @param name the value for project.name
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pid
     *
     * @return the value of project.pid
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pid
     *
     * @param pid the value for project.pid
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.describe_info
     *
     * @return the value of project.describe_info
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public String getDescribeInfo() {
        return describeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.describe_info
     *
     * @param describeInfo the value for project.describe_info
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setDescribeInfo(String describeInfo) {
        this.describeInfo = describeInfo == null ? null : describeInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.duty_person_id
     *
     * @return the value of project.duty_person_id
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public Integer getDutyPersonId() {
        return dutyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.duty_person_id
     *
     * @param dutyPersonId the value for project.duty_person_id
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setDutyPersonId(Integer dutyPersonId) {
        this.dutyPersonId = dutyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.duty_person_name
     *
     * @return the value of project.duty_person_name
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public String getDutyPersonName() {
        return dutyPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.duty_person_name
     *
     * @param dutyPersonName the value for project.duty_person_name
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setDutyPersonName(String dutyPersonName) {
        this.dutyPersonName = dutyPersonName == null ? null : dutyPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.start_time
     *
     * @return the value of project.start_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.start_time
     *
     * @param startTime the value for project.start_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.end_time
     *
     * @return the value of project.end_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.end_time
     *
     * @param endTime the value for project.end_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.need_time
     *
     * @return the value of project.need_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public Integer getNeedTime() {
        return needTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.need_time
     *
     * @param needTime the value for project.need_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setNeedTime(Integer needTime) {
        this.needTime = needTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.status
     *
     * @return the value of project.status
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.status
     *
     * @param status the value for project.status
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.create_time
     *
     * @return the value of project.create_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.create_time
     *
     * @param createTime the value for project.create_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_time
     *
     * @return the value of project.update_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_time
     *
     * @param updateTime the value for project.update_time
     *
     * @mbggenerated Sun Jan 24 14:32:04 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
