package com.example.software.project.development.management.platform.po;

public class RelationProjectToFounds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_project_to_funds.id
     *
     * @mbggenerated Tue Jan 26 23:15:03 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_project_to_funds.project_id
     *
     * @mbggenerated Tue Jan 26 23:15:03 CST 2021
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_project_to_funds.funds_id
     *
     * @mbggenerated Tue Jan 26 23:15:03 CST 2021
     */
    private Integer fundsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_project_to_funds.id
     *
     * @return the value of relation_project_to_funds.id
     *
     * @mbggenerated Tue Jan 26 23:15:03 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_project_to_funds.id
     *
     * @param id the value for relation_project_to_funds.id
     *
     * @mbggenerated Tue Jan 26 23:15:03 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_project_to_funds.project_id
     *
     * @return the value of relation_project_to_funds.project_id
     *
     * @mbggenerated Tue Jan 26 23:15:03 CST 2021
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_project_to_funds.project_id
     *
     * @param projectId the value for relation_project_to_funds.project_id
     *
     * @mbggenerated Tue Jan 26 23:15:03 CST 2021
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_project_to_funds.funds_id
     *
     * @return the value of relation_project_to_funds.funds_id
     *
     * @mbggenerated Tue Jan 26 23:15:03 CST 2021
     */
    public Integer getFundsId() {
        return fundsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_project_to_funds.funds_id
     *
     * @param fundsId the value for relation_project_to_funds.funds_id
     *
     * @mbggenerated Tue Jan 26 23:15:03 CST 2021
     */
    public void setFundsId(Integer fundsId) {
        this.fundsId = fundsId;
    }
}