package com.example.software.project.development.management.platform.po;

public class RelationProjectToLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_project_to_log.id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_project_to_log.log_id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_project_to_log.project_id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_project_to_log.id
     *
     * @return the value of relation_project_to_log.id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_project_to_log.id
     *
     * @param id the value for relation_project_to_log.id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_project_to_log.log_id
     *
     * @return the value of relation_project_to_log.log_id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_project_to_log.log_id
     *
     * @param logId the value for relation_project_to_log.log_id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_project_to_log.project_id
     *
     * @return the value of relation_project_to_log.project_id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_project_to_log.project_id
     *
     * @param projectId the value for relation_project_to_log.project_id
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}