package com.example.software.project.development.management.platform.po;

public class RelationSubscriptionToFounds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_subscription_to_founds.id
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_subscription_to_founds.subscription_id
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    private Integer subscriptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_subscription_to_founds.funds_id
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    private Integer fundsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_subscription_to_founds.id
     *
     * @return the value of relation_subscription_to_founds.id
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_subscription_to_founds.id
     *
     * @param id the value for relation_subscription_to_founds.id
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_subscription_to_founds.subscription_id
     *
     * @return the value of relation_subscription_to_founds.subscription_id
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    public Integer getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_subscription_to_founds.subscription_id
     *
     * @param subscriptionId the value for relation_subscription_to_founds.subscription_id
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    public void setSubscriptionId(Integer subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_subscription_to_founds.funds_id
     *
     * @return the value of relation_subscription_to_founds.funds_id
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    public Integer getFundsId() {
        return fundsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_subscription_to_founds.funds_id
     *
     * @param fundsId the value for relation_subscription_to_founds.funds_id
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    public void setFundsId(Integer fundsId) {
        this.fundsId = fundsId;
    }
}