package com.example.software.project.development.management.platform.po;

public class RelationProjectToCirculation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_project_to_circulation.id
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_project_to_circulation.project_id
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation_project_to_circulation.circulation_id
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    private Integer circulationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_project_to_circulation.id
     *
     * @return the value of relation_project_to_circulation.id
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_project_to_circulation.id
     *
     * @param id the value for relation_project_to_circulation.id
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_project_to_circulation.project_id
     *
     * @return the value of relation_project_to_circulation.project_id
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_project_to_circulation.project_id
     *
     * @param projectId the value for relation_project_to_circulation.project_id
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation_project_to_circulation.circulation_id
     *
     * @return the value of relation_project_to_circulation.circulation_id
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    public Integer getCirculationId() {
        return circulationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation_project_to_circulation.circulation_id
     *
     * @param circulationId the value for relation_project_to_circulation.circulation_id
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    public void setCirculationId(Integer circulationId) {
        this.circulationId = circulationId;
    }
}