package com.example.software.project.development.management.platform.po;

import lombok.Data;

import java.util.Date;

@Data
public class Subscription {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.id
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.status
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.deal_person_id
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    private Integer dealPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.create_time
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.update_time
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    private Date updateTime;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.id
     *
     * @return the value of subscription.id
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.id
     *
     * @param id the value for subscription.id
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.status
     *
     * @return the value of subscription.status
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.status
     *
     * @param status the value for subscription.status
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.deal_person_id
     *
     * @return the value of subscription.deal_person_id
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    public Integer getDealPersonId() {
        return dealPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.deal_person_id
     *
     * @param dealPersonId the value for subscription.deal_person_id
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    public void setDealPersonId(Integer dealPersonId) {
        this.dealPersonId = dealPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.create_time
     *
     * @return the value of subscription.create_time
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.create_time
     *
     * @param createTime the value for subscription.create_time
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.update_time
     *
     * @return the value of subscription.update_time
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.update_time
     *
     * @param updateTime the value for subscription.update_time
     *
     * @mbggenerated Mon Jan 25 16:43:41 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
