package com.example.software.project.development.management.platform.dao;

import com.example.software.project.development.management.platform.po.Circulation;
import com.example.software.project.development.management.platform.po.CirculationExample;
import com.example.software.project.development.management.platform.po.MiddleSubscriptionExample;
import com.example.software.project.development.management.platform.ro.CirculationRo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CirculationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    int countByExample(CirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    int deleteByExample(CirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    int insert(Circulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    int insertSelective(Circulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    List<Circulation> selectByExample(CirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    Circulation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") Circulation record, @Param("example") CirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    int updateByExample(@Param("record") Circulation record, @Param("example") CirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    int updateByPrimaryKeySelective(Circulation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table circulation
     *
     * @mbggenerated Mon Jan 25 21:33:59 CST 2021
     */
    int updateByPrimaryKey(Circulation record);

    List<CirculationRo> selectAllCirculation(MiddleSubscriptionExample middleSubscriptionExample);
}
