package com.example.software.project.development.management.platform.dao;

import com.example.software.project.development.management.platform.po.Funds;
import com.example.software.project.development.management.platform.po.FundsExample;
import com.example.software.project.development.management.platform.ro.FundsRo;
import com.example.software.project.development.management.platform.ro.FundsSearchRoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    int countByExample(FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    int deleteByExample(FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    int insert(Funds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    int insertSelective(Funds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    List<Funds> selectByExample(FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    Funds selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") Funds record, @Param("example") FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    int updateByExample(@Param("record") Funds record, @Param("example") FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    int updateByPrimaryKeySelective(Funds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Tue Jan 26 22:19:44 CST 2021
     */
    int updateByPrimaryKey(Funds record);

    /**
     * 分页获取资金审批情况
     * @param fundsSearchRoExample
     * @return
     */
    List<FundsRo> getFundsList(FundsSearchRoExample fundsSearchRoExample);
}
