package com.example.software.project.development.management.platform.dao;

import com.example.software.project.development.management.platform.po.Log;
import com.example.software.project.development.management.platform.po.LogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int countByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int deleteByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    List<Log> selectByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    Log selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int updateByExample(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int updateByPrimaryKeySelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int updateByPrimaryKey(Log record);

    /**
     * 获取指定项目的全部日志
     * @param projectId
     * @return
     */
    List<Log> getAllProjectLogs(@Param("projectId") Integer projectId,
                                @Param("trueName") String trueName);
}
