package com.example.software.project.development.management.platform.dao;

import com.example.software.project.development.management.platform.po.RelationUserToLog;
import com.example.software.project.development.management.platform.po.RelationUserToLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RelationUserToLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    int countByExample(RelationUserToLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    int deleteByExample(RelationUserToLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    int insert(RelationUserToLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    int insertSelective(RelationUserToLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    List<RelationUserToLog> selectByExample(RelationUserToLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    RelationUserToLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") RelationUserToLog record, @Param("example") RelationUserToLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    int updateByExample(@Param("record") RelationUserToLog record, @Param("example") RelationUserToLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    int updateByPrimaryKeySelective(RelationUserToLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_user_to_log
     *
     * @mbggenerated Sun Jan 24 21:28:08 CST 2021
     */
    int updateByPrimaryKey(RelationUserToLog record);
}
