package com.example.software.project.development.management.platform.dao;

import com.example.software.project.development.management.platform.po.RelationSubscriptionToCirculation;
import com.example.software.project.development.management.platform.po.RelationSubscriptionToCirculationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationSubscriptionToCirculationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    int countByExample(RelationSubscriptionToCirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    int deleteByExample(RelationSubscriptionToCirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    int insert(RelationSubscriptionToCirculation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    int insertSelective(RelationSubscriptionToCirculation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    List<RelationSubscriptionToCirculation> selectByExample(RelationSubscriptionToCirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    RelationSubscriptionToCirculation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    int updateByExampleSelective(@Param("record") RelationSubscriptionToCirculation record, @Param("example") RelationSubscriptionToCirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    int updateByExample(@Param("record") RelationSubscriptionToCirculation record, @Param("example") RelationSubscriptionToCirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    int updateByPrimaryKeySelective(RelationSubscriptionToCirculation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:06:00 CST 2021
     */
    int updateByPrimaryKey(RelationSubscriptionToCirculation record);
}