package com.example.software.project.development.management.platform.dao;

import com.example.software.project.development.management.platform.po.RelationProjectToLog;
import com.example.software.project.development.management.platform.po.RelationProjectToLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationProjectToLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int countByExample(RelationProjectToLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int deleteByExample(RelationProjectToLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int insert(RelationProjectToLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int insertSelective(RelationProjectToLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    List<RelationProjectToLog> selectByExample(RelationProjectToLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    RelationProjectToLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") RelationProjectToLog record, @Param("example") RelationProjectToLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int updateByExample(@Param("record") RelationProjectToLog record, @Param("example") RelationProjectToLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int updateByPrimaryKeySelective(RelationProjectToLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_log
     *
     * @mbggenerated Sun Jan 24 20:44:52 CST 2021
     */
    int updateByPrimaryKey(RelationProjectToLog record);
}