package com.example.software.project.development.management.platform.dao;

import com.example.software.project.development.management.platform.po.RelationProjectToCirculation;
import com.example.software.project.development.management.platform.po.RelationProjectToCirculationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RelationProjectToCirculationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    int countByExample(RelationProjectToCirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    int deleteByExample(RelationProjectToCirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    int insert(RelationProjectToCirculation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    int insertSelective(RelationProjectToCirculation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    List<RelationProjectToCirculation> selectByExample(RelationProjectToCirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    RelationProjectToCirculation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    int updateByExampleSelective(@Param("record") RelationProjectToCirculation record, @Param("example") RelationProjectToCirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    int updateByExample(@Param("record") RelationProjectToCirculation record, @Param("example") RelationProjectToCirculationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    int updateByPrimaryKeySelective(RelationProjectToCirculation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_project_to_circulation
     *
     * @mbggenerated Mon Jan 25 20:14:02 CST 2021
     */
    int updateByPrimaryKey(RelationProjectToCirculation record);
}
