package com.example.software.project.development.management.platform.dao;

import com.example.software.project.development.management.platform.po.RelationSubscriptionToFounds;
import com.example.software.project.development.management.platform.po.RelationSubscriptionToFoundsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationSubscriptionToFoundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    int countByExample(RelationSubscriptionToFoundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    int deleteByExample(RelationSubscriptionToFoundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    int insert(RelationSubscriptionToFounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    int insertSelective(RelationSubscriptionToFounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    List<RelationSubscriptionToFounds> selectByExample(RelationSubscriptionToFoundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    RelationSubscriptionToFounds selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") RelationSubscriptionToFounds record, @Param("example") RelationSubscriptionToFoundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    int updateByExample(@Param("record") RelationSubscriptionToFounds record, @Param("example") RelationSubscriptionToFoundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    int updateByPrimaryKeySelective(RelationSubscriptionToFounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation_subscription_to_founds
     *
     * @mbggenerated Tue Jan 26 21:52:44 CST 2021
     */
    int updateByPrimaryKey(RelationSubscriptionToFounds record);
}